[project]
name = "grapec"
version = "0.4.0"
description = "Declare plain Python classes and serialize them for cross language RPC"
readme = "README.md"
authors = [
    { name = "An Long", email = "aisk1988@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "h2>=4.4.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "grpcio-tools>=1.73.0",
    "grpcio>=1.78.0",
]
